@startuml Reto07
/'Crear una primera versión de diagrama de clases del modelo del dominio del proyecto. Para lograr esto puede seguir los siguientes pasos:
1.Listar a lo sumo cuatro (4) clases conceptuales candidatas
2.Representarlas en un diagrama de clases
3.Añadir las asociaciones necesarias para registrar las relaciones importantes
4.Añadir los atributos necesarios para satisfacer los requisitos de información

Para identificar las clases conceptuales puede utilizar alguna de las siguientes técnicas:
1.Descripción Informal
2.Análisis clásico
3.Análisis del Dominio
'/
/'Clases conceptuales: 
Curso de extensión: solución propuesta por la DEU, siendo estas formaciones especiales de interés general dirigidos a la ampliación del conocimiento técnico y profesional, de habilidades u oficios y hasta para el crecimiento cultural, social y personal, no conducente al reconocimiento de créditos académicos.
Proponente: Persona natural o jurídica la cual puede proponer cursos de extensión 
Administrador:  Representa a la DEU o a la coordinación de extensión de Facultad quienes evalúan y aprueban el curso de extensión.
Aliado: puede proponer y ejecutar varios cursos de extensión.
Solicitud Curso: solicitud del curso propuesto por el proponente y evaluado por el administrador
'/
class Curso_extension{
- id: interger
- nombre: string
- objetivos: List<string>
- fundamentacion: string
- estrategias_evaluacion: List<string>
- duración: interger
- cronograma_ejecucion: date
}

class Proponente {
- cédula_identidad: string
- título universitario: string
- RIF : string
- certificados_declaracion_islr: List<string>
- resumen_curricular: string
- documentos_especificos: List<DocumentoEspecificos>
}

class Administrador {
- id: interger
- nombre: string
- facultad:string
- capacidad _evaluacion: boolean
}

class Aliado {
- id: interger
- porcentaje_lucro: floated
- documentos_presentados: List<DocumentosPresentados>
- cronograma_ejecucion: date
- estructura_costos_ingreso: Map<string, float>
}

class SolicitudCurso{
-NombreCurso : string
-DuracionCurso: int
-Cronograma_realizacion: string
-perfil_docente: string
-Curriculum: string
}
SolicitudCurso "propone"<-- Proponente
Administrador "evaluar"--> SolicitudCurso
Curso_extension "evaluado por" --> Administrador
Curso_extension "ejecuta" --> Aliado
Aliado "ejecutado por"--> Curso_extension
SolicitudCurso --|> Curso_extension
@enduml
