@startuml Reto07
/'Crear una primera versión de diagrama de clases del modelo del dominio del proyecto. Para lograr esto puede seguir los siguientes pasos:
1.Listar a lo sumo cuatro (4) clases conceptuales candidatas
2.Representarlas en un diagrama de clases
3.Añadir las asociaciones necesarias para registrar las relaciones importantes
4.Añadir los atributos necesarios para satisfacer los requisitos de información

Para identificar las clases conceptuales puede utilizar alguna de las siguientes técnicas:
1.Descripción Informal
2.Análisis clásico
3.Análisis del Dominio
'/
/'Clases conceptuales: 
Curso de extensión: solución propuesta por la DEU, siendo estas formaciones especiales de interés general dirigidos a la ampliación del conocimiento técnico y profesional, de habilidades u oficios y hasta para el crecimiento cultural, social y personal, no conducente al reconocimiento de créditos académicos.
Proponente: Persona natural o jurídica la cual puede proponer cursos de extensión 
Administrador:  Representa a la DEU o a la coordinación de extensión de Facultad quienes evalúan y aprueban el curso de extensión.
Aliado: puede proponer y ejecutar varios cursos de extensión.
Solicitud Curso: solicitud del curso propuesto por el proponente y evaluado por el administrador
'/
class Curso_extensión{
id
nombre
objetivos
fundamentacion
estrategias_evaluacion
duración
cronograma_ejecucion
}

class Proponente {
cédula_identidad
título universitario
RIF
certificados_declaracion_islr
resumen_curricular
documentos_especificos
}

class Administrador {
id
nombre
facultad
capacidad _evaluacion
}

class Aliado {
id
porcentaje_lucro
documentos_presentados
cronograma_ejecucion
estructura_costos_ingreso
}

class SolicitudCurso{
NombreCurso
DuracionCurso
Cronograma_realizacion
perfil_docente
Curriculum
}

SolicitudCurso <--"1..*" Proponente : Propone
Administrador "evaluar"-->SolicitudCurso
Curso_extensión -->"1..*" Administrador: evaluado por
Curso_extensión  *-- "1..*" Aliado : ejecutado por
SolicitudCurso --|> Curso_extensión
@enduml
